export const TEXTS = {
  app: {
    name: 'PlayOne',
    description: 'Juego de cartas rápido para jugar en línea o en solitario.',
    cardBackLabel: 'UNO',
  },
  common: {
    youLabel: '(Tú)',
    loading: 'Cargando...',
  },
  home: {
    titleIntro: 'EL JUEGO',
    titleHighlight: 'DE CARTAS DEFINITIVO',
    description:
      'Disfruta el clásico reimaginado. Juega en solitario contra bots inteligentes o reta a tus amigos por P2P. Sin registro.',
    playOnline: 'JUGAR EN LÍNEA',
    playSolo: 'JUGAR',
    github: 'GitHub',
  },
  lobby: {
    lobbyTitle: 'Lobby de PlayOne',
    roomId: 'ID de sala',
    players: 'Jugadores',
    startGame: 'INICIAR',
    addBot: '+ BOT',
    minPlayers: 'Se necesitan mínimo 2 jugadores',
    waitingHost: 'Esperando a que el host inicie...',
    enterNickname: 'Ingresa tu apodo',
    roomNameOptional: 'Nombre de sala (opcional)',
    createRoom: 'CREAR SALA',
    playSolo: 'JUGAR SOLO',
    orJoin: 'O UNIRSE',
    pasteRoomId: 'Pega el ID de sala',
    join: 'UNIRSE',
    initializingHost: 'Iniciando host...',
    connectingHost: 'Conectando al host...',
    errors: {
      nameRequired: 'Se requiere nombre',
      nameAndRoomRequired: 'Nombre e ID de sala requeridos',
      startHost: 'No se pudo iniciar el host',
      startSolo: 'No se pudo iniciar el modo solo',
    },
  },
  game: {
    drawStack: (count: number) => `¡ROBA ${count}!`,
    start: 'INICIO',
    chooseColor: 'Elige el siguiente color',
    colors: {
      red: 'ROJO',
      green: 'VERDE',
      blue: 'AZUL',
      yellow: 'AMARILLO',
    },
    victory: '¡VICTORIA!',
    playAgain: 'JUGAR DE NUEVO',
    unknownPlayer: 'Desconocido',
    defaultPlayerName: 'Jugador',
  },
  debug: {
    title: 'Depurar motor + bots',
    defaultPlayers: ['Alicia', 'Beto (Bot)', 'Carlos (Bot)'],
    botNames: ['Beto', 'Carlos'],
    enableBot: (name: string) => `Activar bot para ${name}`,
    publicState: 'Estado público',
    controls: (name: string) => `Controles (Turno: ${name})`,
    pendingDraw: 'Robos pendientes',
    topCard: 'Carta superior',
    currentColor: 'Color actual',
    hand: (count: number) => `Mano (${count})`,
    drawCard: 'ROBA CARTA',
    chooseColor: 'ELEGIR COLOR',
    restartGame: 'REINICIAR PARTIDA',
  },
};
