export const TEXTS_ES = {
  app: {
    name: 'PlayOne',
    description: 'Juego de cartas rápido para jugar en línea o en solitario.',
    cardBackLabel: 'UNO',
  },
  common: {
    youLabel: '(Tú)',
    loading: 'Cargando...',
    save: 'Guardar',
    play: 'Jugar',
  },
  home: {
    titleIntro: 'EL JUEGO',
    titleHighlight: 'DE CARTAS DEFINITIVO',
    description:
      'Disfruta el clásico reimaginado. Juega en solitario contra bots inteligentes o reta a tus amigos por P2P. Sin registro.',
    playOnline: 'JUGAR EN LÍNEA',
    playSolo: 'JUGAR',
    settings: 'CONFIGURACIONES',
    github: 'GitHub',
  },
  lobby: {
    lobbyTitle: 'Lobby de PlayOne',
    roomId: 'ID de sala',
    players: 'Jugadores',
    startGame: 'INICIAR',
    addBot: '+ BOT',
    minPlayers: 'Se necesitan mínimo 2 jugadores',
    waitingHost: 'Esperando a que el host inicie...',
    enterNickname: 'Ingresa tu apodo',
    roomNameOptional: 'Nombre de sala (opcional)',
    createRoom: 'CREAR SALA',
    playSolo: 'JUGAR SOLO',
    orJoin: 'O UNIRSE',
    pasteRoomId: 'Pega el ID de sala',
    join: 'UNIRSE',
    initializingHost: 'Iniciando host...',
    connectingHost: 'Conectando al host...',
    errors: {
      nameRequired: 'Se requiere nombre',
      nameAndRoomRequired: 'Nombre e ID de sala requeridos',
      startHost: 'No se pudo iniciar el host',
      startSolo: 'No se pudo iniciar el modo solo',
    },
  },
  settings: {
    title: 'Configuraciones',
    subtitle: 'Personaliza tu partida local',
    playerNameLabel: 'Nombre del jugador',
    nicknameLabel: 'Apodo',
    nicknamePlaceholder: 'Tu apodo',
    difficultyLabel: 'Dificultad',
    languageLabel: 'Idioma',
    difficultyDescriptions: {
      EASY: 'Bots relajados, más caóticos y poco agresivos.',
      NORMAL: 'Bots balanceados con decisiones moderadas.',
      HARD: 'Bots tácticos, conservan comodines y atacan mejor.',
      EXPERT: 'Bots muy disciplinados, con memoria y targeting máximo.',
    },
    languageOptions: {
      es: 'Español',
      en: 'Inglés',
    },
  },
  game: {
    drawStack: (count: number) => `¡ROBA ${count}!`,
    start: 'INICIO',
    chooseColor: 'Elige el siguiente color',
    colors: {
      red: 'ROJO',
      green: 'VERDE',
      blue: 'AZUL',
      yellow: 'AMARILLO',
    },
    victory: '¡VICTORIA!',
    playAgain: 'JUGAR DE NUEVO',
    unknownPlayer: 'Desconocido',
    defaultPlayerName: 'Jugador',
  },
  debug: {
    title: 'Depurar motor + bots',
    defaultPlayers: ['Alicia', 'Beto (Bot)', 'Carlos (Bot)'],
    botNames: ['Beto', 'Carlos'],
    enableBot: (name: string) => `Activar bot para ${name}`,
    publicState: 'Estado público',
    controls: (name: string) => `Controles (Turno: ${name})`,
    pendingDraw: 'Robos pendientes',
    topCard: 'Carta superior',
    currentColor: 'Color actual',
    hand: (count: number) => `Mano (${count})`,
    drawCard: 'ROBA CARTA',
    chooseColor: 'ELEGIR COLOR',
    restartGame: 'REINICIAR PARTIDA',
  },
};

export const TEXTS_EN = {
  app: {
    name: 'PlayOne',
    description: 'Fast-paced card game to play online or solo.',
    cardBackLabel: 'UNO',
  },
  common: {
    youLabel: '(You)',
    loading: 'Loading...',
    save: 'Save',
    play: 'Play',
  },
  home: {
    titleIntro: 'THE',
    titleHighlight: 'ULTIMATE CARD GAME',
    description:
      'Enjoy the classic reimagined. Play solo against smart bots or challenge friends via P2P. No registration.',
    playOnline: 'PLAY ONLINE',
    playSolo: 'PLAY',
    settings: 'SETTINGS',
    github: 'GitHub',
  },
  lobby: {
    lobbyTitle: 'PlayOne Lobby',
    roomId: 'Room ID',
    players: 'Players',
    startGame: 'START',
    addBot: '+ BOT',
    minPlayers: 'At least 2 players are required',
    waitingHost: 'Waiting for host to start...',
    enterNickname: 'Enter your nickname',
    roomNameOptional: 'Room name (optional)',
    createRoom: 'CREATE ROOM',
    playSolo: 'PLAY SOLO',
    orJoin: 'OR JOIN',
    pasteRoomId: 'Paste the room ID',
    join: 'JOIN',
    initializingHost: 'Starting host...',
    connectingHost: 'Connecting to host...',
    errors: {
      nameRequired: 'Name is required',
      nameAndRoomRequired: 'Name and room ID are required',
      startHost: 'Could not start host',
      startSolo: 'Could not start solo mode',
    },
  },
  settings: {
    title: 'Settings',
    subtitle: 'Customize your local match',
    playerNameLabel: 'Player name',
    nicknameLabel: 'Nickname',
    nicknamePlaceholder: 'Your nickname',
    difficultyLabel: 'Difficulty',
    languageLabel: 'Language',
    difficultyDescriptions: {
      EASY: 'Relaxed bots, more chaotic and less aggressive.',
      NORMAL: 'Balanced bots with moderate decisions.',
      HARD: 'Tactical bots that conserve wilds and strike well.',
      EXPERT: 'Highly disciplined bots with strong memory and targeting.',
    },
    languageOptions: {
      es: 'Spanish',
      en: 'English',
    },
  },
  game: {
    drawStack: (count: number) => `DRAW ${count}!`,
    start: 'START',
    chooseColor: 'Choose the next color',
    colors: {
      red: 'RED',
      green: 'GREEN',
      blue: 'BLUE',
      yellow: 'YELLOW',
    },
    victory: 'VICTORY!',
    playAgain: 'PLAY AGAIN',
    unknownPlayer: 'Unknown',
    defaultPlayerName: 'Player',
  },
  debug: {
    title: 'Debug engine + bots',
    defaultPlayers: ['Alicia', 'Beto (Bot)', 'Carlos (Bot)'],
    botNames: ['Beto', 'Carlos'],
    enableBot: (name: string) => `Enable bot for ${name}`,
    publicState: 'Public state',
    controls: (name: string) => `Controls (Turn: ${name})`,
    pendingDraw: 'Pending draws',
    topCard: 'Top card',
    currentColor: 'Current color',
    hand: (count: number) => `Hand (${count})`,
    drawCard: 'DRAW CARD',
    chooseColor: 'CHOOSE COLOR',
    restartGame: 'RESTART GAME',
  },
};

export const TEXTS = TEXTS_ES;
